server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: bookstore-super-secret-key-for-jwt-signing-2024
  expiry: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

